# This recipe looks for folders that have tif image files ending with 0.tif, 1.tif, and 2.tif
# For each tif file, it applies the background thresholding used in MCS Detect.
# It tests the z-filter from 1 to 2 at 0.5 increments.
# For each original tif file, you will get, per z-value a masked and binary mask file. 
# For each tif file you will get a concatenated csv file of objects and their intensity after filtering.
[global]
act_on_success=true
inputdirectory = "testdir"
[any]
all=true
conditions = ["is_dir"]
actions=[["filter_mcsdetect", 1, 0.5, 2, "*[0-2].tif"]]